package schema

// Code generated by go-ipld-prime gengo.  DO NOT EDIT.

import (
	"github.com/ipld/go-ipld-prime/datamodel"
)

var _ datamodel.Node = nil // suppress errors when this dependency is not referenced
// Type is a struct embeding a NodePrototype/Type for every Node implementation in this package.
// One of its major uses is to start the construction of a value.
// You can use it like this:
//
// 		schema.Type.YourTypeName.NewBuilder().BeginMap() //...
//
// and:
//
// 		schema.Type.OtherTypeName.NewBuilder().AssignString("x") // ...
//
var Type typeSlab

type typeSlab struct {
	Bytes            _Bytes__Prototype
	Bytes__Repr      _Bytes__ReprPrototype
	Communites       _Communites__Prototype
	Communites__Repr _Communites__ReprPrototype
	Community        _Community__Prototype
	Community__Repr  _Community__ReprPrototype
	Image            _Image__Prototype
	Image__Repr      _Image__ReprPrototype
	Int              _Int__Prototype
	Int__Repr        _Int__ReprPrototype
	String           _String__Prototype
	String__Repr     _String__ReprPrototype
	World            _World__Prototype
	World__Repr      _World__ReprPrototype
}

// --- type definitions follow ---

// Bytes matches the IPLD Schema type "Bytes".  It has bytes kind.
type Bytes = *_Bytes
type _Bytes struct{ x []byte }

// Communites matches the IPLD Schema type "Communites".  It has list kind.
type Communites = *_Communites
type _Communites struct {
	x []_Community
}

// Community matches the IPLD Schema type "Community".  It has struct type-kind, and may be interrogated like map kind.
type Community = *_Community
type _Community struct {
	Name  _String
	Image _Image__Maybe
}

// Image matches the IPLD Schema type "Image".  It has struct type-kind, and may be interrogated like map kind.
type Image = *_Image
type _Image struct {
	Data _Bytes
	Size _Int
}

// Int matches the IPLD Schema type "Int".  It has int kind.
type Int = *_Int
type _Int struct{ x int64 }

// String matches the IPLD Schema type "String".  It has string kind.
type String = *_String
type _String struct{ x string }

// World matches the IPLD Schema type "World".  It has struct type-kind, and may be interrogated like map kind.
type World = *_World
type _World struct {
	Communites _Communites
}
