// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ProfileInput struct {
	Name string `json:"name"`
}

type StoryInput struct {
	Name    string `json:"name"`
	OwnerID string `json:"ownerId"`
}
